[package]
name = "benchmark-rs"
version = "0.0.1-alpha"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
chrono = "0.4.24"
json = "0.12.4"
rand = "0.8.5"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
statrs = "0.16.0"
num-traits = "0.2.15"
thiserror = "1.0.40"
